on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-review-checklist:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # - name: Add review checklist
      #   run: |
      #     gh pr comment --body-file .github/review-checklist.md
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Wololo!'
            })