on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-review-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Read review checklist into environment variable
        run: |
          {
            echo 'REVIEW_CHECKLIST<<REVIEW_CHECKLIST_EOF'
            cat .github/review-checklist.md
            echo
            echo 'REVIEW_CHECKLIST_EOF'
          } >> "$GITHUB_ENV"
      - name: Add review checklist
        uses: actions/github-script@v6
        with:
          script: |
            const { REVIEW_CHECKLIST } = process.env
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${REVIEW_CHECKLIST}'
            })